In [4]:
import sklearn
from sklearn.datasets import load_iris

print(sklearn.__version__)

iris = load_iris()
print(iris.data.shape)

1.4.1.post1
(150, 4)


In [2]:
# UNIT 2 
#  Pre - Processing

# Mean Removal

import  numpy as np
a = np.array([[2],[4],[6],[8],[10]])

print(a)

mean = np.mean(a)
print(mean)

cen = a-mean
print(cen)

[[ 2]
 [ 4]
 [ 6]
 [ 8]
 [10]]
6.0
[[-4.]
 [-2.]
 [ 0.]
 [ 2.]
 [ 4.]]


In [3]:
# Scaling

import numpy as np 
a = np.array([[10],[20],[30],[40],[50]])
print(a)

min = np.min(a)
print(min)

max = np.max(a)
print(max)

scal = (a-min)/(max-min)
print(scal)

[[10]
 [20]
 [30]
 [40]
 [50]]
10
50
[[0.  ]
 [0.25]
 [0.5 ]
 [0.75]
 [1.  ]]


In [5]:
# pre processing
# 3. normalization

import numpy as np
from sklearn import preprocessing
# scikit learn

data = ([[3,4],[1,2],[5,12]])
print(data)

# L - lebesgue space
nl1 = preprocessing.normalize(data,norm='l1')
print(nl1)

nl2 = preprocessing.normalize(data,norm='l2')
print(nl2)

[[3, 4], [1, 2], [5, 12]]
[[0.42857143 0.57142857]
 [0.33333333 0.66666667]
 [0.29411765 0.70588235]]
[[0.6        0.8       ]
 [0.4472136  0.89442719]
 [0.38461538 0.92307692]]


In [12]:
# pre processing
#binarization

import numpy as np
from sklearn import preprocessing

data = np.array([[5],[7],[12],[15],[25]])
print(data)
print('*'*15)

bin = preprocessing.Binarizer(threshold=7).transform(data)
#  applies binarizer to each element
print(bin)

[[ 5]
 [ 7]
 [12]
 [15]
 [25]]
***************
[[0]
 [0]
 [1]
 [1]
 [1]]


In [9]:
# pre processng 
# label endoding
from sklearn import preprocessing

label  = ['apple','mango','cherry','dragon fruit','grapes']
print(label)

# load the encoder
lblen = preprocessing.LabelEncoder()

# fit and transform
op = lblen.fit_transform(label)
print(op)

['apple', 'mango', 'cherry', 'dragon fruit', 'grapes']
[0 4 1 2 3]
